// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tiny_haven.Server.Data;

#nullable disable

namespace tiny_haven.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251216130026_RedoDatabase")]
    partial class RedoDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("tiny_haven.Server.Models.Asset", b =>
                {
                    b.Property<int>("AssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Collision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SpanX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpanY")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Visible")
                        .HasColumnType("INTEGER");

                    b.HasKey("AssetId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("tiny_haven.Server.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("tiny_haven.Server.Models.InteractionMap", b =>
                {
                    b.Property<int>("InteractionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("xOffsetEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("xOffsetStart")
                        .HasColumnType("INTEGER");

                    b.Property<int>("yOffsetEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("yOffsetStart")
                        .HasColumnType("INTEGER");

                    b.HasKey("InteractionId");

                    b.HasIndex("LocationId");

                    b.HasIndex("QuestId");

                    b.ToTable("InteractionMaps");
                });

            modelBuilder.Entity("tiny_haven.Server.Models.LocationMap", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationY")
                        .HasColumnType("INTEGER");

                    b.HasKey("LocationId");

                    b.HasIndex("AssetId");

                    b.ToTable("LocationMaps");
                });

            modelBuilder.Entity("tiny_haven.Server.Models.Quest", b =>
                {
                    b.Property<int>("QuestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ItemQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("NextQuestId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RewardAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RewardItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("WantedItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("QuestId");

                    b.HasIndex("NextQuestId");

                    b.HasIndex("RewardItemId");

                    b.HasIndex("WantedItemId");

                    b.ToTable("Quests");
                });

            modelBuilder.Entity("tiny_haven.Server.Models.Asset", b =>
                {
                    b.HasOne("tiny_haven.Server.Models.Category", "Category")
                        .WithMany("Assets")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("tiny_haven.Server.Models.InteractionMap", b =>
                {
                    b.HasOne("tiny_haven.Server.Models.LocationMap", "LocationMap")
                        .WithMany("InteractionMaps")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tiny_haven.Server.Models.Quest", "Quest")
                        .WithMany("InteractionMaps")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocationMap");

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("tiny_haven.Server.Models.LocationMap", b =>
                {
                    b.HasOne("tiny_haven.Server.Models.Asset", "Asset")
                        .WithMany("LocationMaps")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("tiny_haven.Server.Models.Quest", b =>
                {
                    b.HasOne("tiny_haven.Server.Models.Quest", "NextQuest")
                        .WithMany()
                        .HasForeignKey("NextQuestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("tiny_haven.Server.Models.Asset", "RewardItem")
                        .WithMany("RewardInQuests")
                        .HasForeignKey("RewardItemId");

                    b.HasOne("tiny_haven.Server.Models.Asset", "WantedItem")
                        .WithMany("WantedInQuests")
                        .HasForeignKey("WantedItemId");

                    b.Navigation("NextQuest");

                    b.Navigation("RewardItem");

                    b.Navigation("WantedItem");
                });

            modelBuilder.Entity("tiny_haven.Server.Models.Asset", b =>
                {
                    b.Navigation("LocationMaps");

                    b.Navigation("RewardInQuests");

                    b.Navigation("WantedInQuests");
                });

            modelBuilder.Entity("tiny_haven.Server.Models.Category", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("tiny_haven.Server.Models.LocationMap", b =>
                {
                    b.Navigation("InteractionMaps");
                });

            modelBuilder.Entity("tiny_haven.Server.Models.Quest", b =>
                {
                    b.Navigation("InteractionMaps");
                });
#pragma warning restore 612, 618
        }
    }
}
