// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tiny_haven.Server.Data;

#nullable disable

namespace tiny_haven.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("tiny_haven.Server.Models.Asset", b =>
                {
                    b.Property<int>("AssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Collision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SpanX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpanY")
                        .HasColumnType("INTEGER");

                    b.HasKey("AssetId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            AssetId = 1,
                            CategoryId = 1,
                            Collision = false,
                            ImageUrl = "images/bush_smurfberries.svg",
                            Name = "bush_smurfberries",
                            SpanX = 1,
                            SpanY = 1
                        },
                        new
                        {
                            AssetId = 2,
                            CategoryId = 2,
                            Collision = true,
                            ImageUrl = "images/house_red.svg",
                            Name = "house_red",
                            SpanX = 2,
                            SpanY = 2
                        },
                        new
                        {
                            AssetId = 3,
                            CategoryId = 2,
                            Collision = true,
                            ImageUrl = "images/house_blue.svg",
                            Name = "house_blue",
                            SpanX = 2,
                            SpanY = 2
                        },
                        new
                        {
                            AssetId = 4,
                            CategoryId = 3,
                            Collision = true,
                            ImageUrl = "images/smurf.svg",
                            Name = "smurf",
                            SpanX = 1,
                            SpanY = 1
                        },
                        new
                        {
                            AssetId = 5,
                            CategoryId = 3,
                            Collision = true,
                            ImageUrl = "images/gargamel.svg",
                            Name = "gargamel",
                            SpanX = 3,
                            SpanY = 4
                        },
                        new
                        {
                            AssetId = 6,
                            CategoryId = 1,
                            Collision = false,
                            ImageUrl = "images/stone.svg",
                            Name = "stone",
                            SpanX = 1,
                            SpanY = 1
                        },
                        new
                        {
                            AssetId = 7,
                            CategoryId = 1,
                            Collision = false,
                            ImageUrl = "images/wood.svg",
                            Name = "wood",
                            SpanX = 1,
                            SpanY = 1
                        });
                });

            modelBuilder.Entity("tiny_haven.Server.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Nature"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Buildings"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Characters"
                        });
                });

            modelBuilder.Entity("tiny_haven.Server.Models.InteractionMap", b =>
                {
                    b.Property<int>("InteractionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("InteractionTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QuestId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("xOffsetEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("xOffsetStart")
                        .HasColumnType("INTEGER");

                    b.Property<int>("yOffsetEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("yOffsetStart")
                        .HasColumnType("INTEGER");

                    b.HasKey("InteractionId");

                    b.HasIndex("InteractionTypeId");

                    b.HasIndex("LocationId");

                    b.HasIndex("QuestId");

                    b.ToTable("InteractionMaps");
                });

            modelBuilder.Entity("tiny_haven.Server.Models.InteractionType", b =>
                {
                    b.Property<int>("InteractionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("InteractionTypeId");

                    b.ToTable("InteractionTypes");
                });

            modelBuilder.Entity("tiny_haven.Server.Models.LocationMap", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationY")
                        .HasColumnType("INTEGER");

                    b.HasKey("LocationId");

                    b.HasIndex("AssetId");

                    b.ToTable("LocationMaps");
                });

            modelBuilder.Entity("tiny_haven.Server.Models.Quest", b =>
                {
                    b.Property<int>("QuestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("NextQuestId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RewardAmount")
                        .HasColumnType("INTEGER");

                    b.HasKey("QuestId");

                    b.HasIndex("AssetId");

                    b.HasIndex("NextQuestId");

                    b.ToTable("Quests");
                });

            modelBuilder.Entity("tiny_haven.Server.Models.Asset", b =>
                {
                    b.HasOne("tiny_haven.Server.Models.Category", "Category")
                        .WithMany("Assets")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("tiny_haven.Server.Models.InteractionMap", b =>
                {
                    b.HasOne("tiny_haven.Server.Models.InteractionType", "InteractionType")
                        .WithMany("InteractionMaps")
                        .HasForeignKey("InteractionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tiny_haven.Server.Models.LocationMap", "LocationMap")
                        .WithMany("InteractionMaps")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tiny_haven.Server.Models.Quest", "Quest")
                        .WithMany("InteractionMaps")
                        .HasForeignKey("QuestId");

                    b.Navigation("InteractionType");

                    b.Navigation("LocationMap");

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("tiny_haven.Server.Models.LocationMap", b =>
                {
                    b.HasOne("tiny_haven.Server.Models.Asset", "Asset")
                        .WithMany("LocationMaps")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("tiny_haven.Server.Models.Quest", b =>
                {
                    b.HasOne("tiny_haven.Server.Models.Asset", "Asset")
                        .WithMany("Quests")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tiny_haven.Server.Models.Quest", "NextQuest")
                        .WithMany()
                        .HasForeignKey("NextQuestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Asset");

                    b.Navigation("NextQuest");
                });

            modelBuilder.Entity("tiny_haven.Server.Models.Asset", b =>
                {
                    b.Navigation("LocationMaps");

                    b.Navigation("Quests");
                });

            modelBuilder.Entity("tiny_haven.Server.Models.Category", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("tiny_haven.Server.Models.InteractionType", b =>
                {
                    b.Navigation("InteractionMaps");
                });

            modelBuilder.Entity("tiny_haven.Server.Models.LocationMap", b =>
                {
                    b.Navigation("InteractionMaps");
                });

            modelBuilder.Entity("tiny_haven.Server.Models.Quest", b =>
                {
                    b.Navigation("InteractionMaps");
                });
#pragma warning restore 612, 618
        }
    }
}
